### ISSUE TITLE
Fix tox/testing matrix

### ISSUE THREAD

**Issue by tony** [hellysmile/django-activeurl#23]
@hellysmile next thing, let's get CI greenlighting

What do you want to have happen re: old django, 1.7 and less. Keep or let them go?

- There is an issue with htmlparse in some of the test suites. Using a newer django version fixes it. [Something happened in django 1.4.2](https://docs.djangoproject.com/en/1.11/releases/1.4.2/)
- There's issues with the testbed and django url routes ([``patterns()`` deprecated in 1.8](https://docs.djangoproject.com/en/1.11/releases/1.8/#django-conf-urls-patterns)), that's fixed via newer django versions too

**Comment by hellysmile** [comment]
Can we just make next realease with support of Django versions which is officially supported right now?

**Comment by tony** [comment]
Which could be 1.8+, and python 2.7+

Yep.

**Comment by hellysmile** [comment]
Can You push AUTHORS and add all https://github.com/hellysmile/django-activeurl/graphs/contributors this guys?

**Comment by hellysmile** [comment]
According to https://www.djangoproject.com/download/
we need to leave 1.8, 1.10 and 1.11
As well it will be great to start testing 2.0, maybe just django master branch?

**Comment by tony** [comment]
Good point, we can opt out of 1.9.

And yeah nothing wrong with adding travis/tox tests to master.

**Comment by hellysmile** [comment]
We can drop frosted linter as well, this lib is dead.

Another great step forward can be replace nose by pytest

Right now here is copy of test matrix from tox to travis, which can be omitted - here is an example how we do it https://github.com/wikibusiness/aioelasticsearch

**Comment by tony** [comment]
Fine with me.

Also, love pytest.

**Comment by tony** [comment]
Fixed #29
