### ISSUE TITLE
RTD + Sphinx docs

### ISSUE THREAD

**Issue by tony** [hellysmile/django-activeurl#24]
Add sphinx docs

**Comment by tony** [comment]
@hellysmile do you have a RTD account?  Could you make one and get this repo setup w/ it?

**Comment by hellysmile** [comment]
Does http://django-activeurl.readthedocs.io/en/latest/ works for You?

**Comment by tony** [comment]
Yes, let's add it to the repo description?

**Comment by hellysmile** [comment]
Right now docs is bit limited, it is just symlink from readme...
Do You think it makes sense? If Yes, You are more then welcome!

**Comment by tony** [comment]
Sphinx needs an ``.. toctree::`` in the ``index.rst``, e.g. https://raw.githubusercontent.com/tony/libvcs/master/doc/index.rst

What do you think about breaking README.rst up into pages?

**Comment by hellysmile** [comment]
You are welcome to do it Your way!

**Comment by tony** [comment]
It'd be helpful to get push access on this repo. Are you ok w/ that? And pypi/rtd? Could you add my username to those so I can push releases and update rtd settings?  I'm tony on RTD and git-pull on Pypi.

**Comment by hellysmile** [comment]
rtd access was just granted!

I am not fully sure regarding future of django-activeurl, maybe I need to talk from some one from https://github.com/jazzband for example and move it there. Ill wait about pypi for a bit.

**Comment by tony** [comment]
Yes anything to make the project under better maintainership is good. 👍

**Comment by tony** [comment]
Can you replace the link to pypi with RTD?  http://django-activeurl.readthedocs.io/en/latest/

<img width="847" alt="screen shot 2017-07-27 at 6 52 27 pm" src="https://user-images.githubusercontent.com/26336/28696701-cac2bad2-72fc-11e7-8a24-361f3ac48711.png">

**Comment by hellysmile** [comment]
Replaced

**Comment by hellysmile** [comment]
I've fixed some code styling today and matrix build

I can do release, when You say that we are ready and docs ready!

Thanks for great job!

**Comment by hellysmile** [comment]
@tony ping ;)

**Comment by tony** [comment]
I think we're ok to tag a new release right now. no need to wait. We can always update docs after through master.

remember the version is stored in *__about__.py* now

When you release, do this:

``git tag <version>``

``git push --tags``

that way we got a mark in git for what we released, along with pypi.

**Comment by hellysmile** [comment]
just released tag and pypi!
