### ISSUE TITLE
Okay to only test Python 3 + Django 2.2 and up?

### ISSUE THREAD

**Issue by tony** [hellysmile/django-activeurl#46]
@hellysmile 

Any opinion on this?

https://docs.djangoproject.com/en/3.0/releases/3.0/

> Following the release of Django 3.0, we suggest that third-party app authors drop support for all versions of Django prior to 2.2.

We could clean up travis / CI a lot if we follow that.

**Comment by hellysmile** [comment]
Hey, fine for me, thanks a lot for maintaining

**Comment by tony** [comment]
Fixed in merging #48 / f6a1ee6
